// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GuestGeneratorController from "./guest_generator_controller"
import HelloController from "./hello_controller"
import OnboardingController from "./onboarding_controller"
import PasswordGeneratorController from "./password_generator_controller"
import PasswordRevealController from "./password_reveal_controller"
import PasswordRowController from "./password_row_controller"
application.register("guest-generator", GuestGeneratorController)
application.register("hello", HelloController)
application.register("onboarding", OnboardingController)
application.register("password-generator", PasswordGeneratorController)
application.register("password-reveal", PasswordRevealController)
application.register("password-row", PasswordRowController)
